# Generated by Django 5.0.2 on 2024-02-21 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('poi_external_id', models.CharField(max_length=255)),
                ('poi_name', models.CharField(max_length=255)),
                ('poi_latitude', models.FloatField()),
                ('poi_longitude', models.FloatField()),
                ('poi_category', models.CharField(max_length=255)),
                ('poi_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('point_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='point_of_interest.pointofinterest')),
            ],
        ),
    ]
